language: python
python: 3.6

git:
  lfs_skip_smudge: true

install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
- bash ~/miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda env create -f environment.yml
- source activate crash-model

script:
- cd src
- pylint pipeline.py initialize_city.py data/*.py visualization/*.py data_standardization/*.py models/*.py features/*.py tools/*.py
- py.test --cov=./

after_success:
- codecov